{
 "title": "Subgraph Indexer Service Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "deployment" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br/> \n<center> \n  <h1>Indexer Service Queries</h1> \n</center>"
   }
  },
  {
   "title": "Indexer Service Queries Total (last 60 min)",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_total[60m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "sum(increase(indexer_service_queries_failed[60m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Service Queries Total ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_queries_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Service Queries Duration by Bucket",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(indexer_service_query_duration_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Execution Time Histogram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
   "repeat": "deployment",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_query_duration_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Service Queries Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_total[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Service Queries Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_total[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Service Queries Total vs Failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Service Queries Failed by Subgraph",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_failed[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Service Indexer Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(indexer_error[5m])", "legendFormat": "{{job}}-{{code}}" }
   ]
  },
  {
   "title": "Service Queries Failed %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(indexer_service_queries_failed[1m])/increase(indexer_service_queries_total[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<br/> \n<center> \n  <h2>Indexer Service Queries by Node</h2> \n</center>"
   }
  },
  {
   "title": "Service Queries Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_total[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Service Queries Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_total[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Service Queries Total vs Failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_total[1m])) by (job)",
     "legendFormat": "Total-{{job}}"
    },
    {
     "expr": "sum(increase(indexer_service_queries_failed[1m])) by (job)",
     "legendFormat": "Failed-{{job}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<br/> \n<center> \n  <h1>Indexer Service Metrics</h1> \n</center>"
   }
  },
  {
   "title": "Service Cost Model Queries Invalid ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(indexer_service_cost_model_queries_invalid[1m])"
    }
   ]
  },
  {
   "title": "Service Channel Message Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_channel_messages_total[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Service Cost Model Batch Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(indexer_service_cost_model_batch_queries[1m])"
    }
   ]
  },
  {
   "title": "Service Channel Message OK",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(indexer_Service_channel_messages_ok[5m])"
    }
   ]
  },
  {
   "title": "Service Cost Model Batch Queries Failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(indexer_service_cost_model_batch_queries_failed[1m])"
    }
   ]
  },
  {
   "title": "Service Cost Model Batch Queries Failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(indexer_service_cost_model_batch_queries_failed[1m])"
    }
   ]
  },
  {
   "title": "Service Cost Model Batch Queries Invalid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(indexer_service_cost_model_batch_queries_invalid[1m])"
    }
   ]
  },
  {
   "title": "Service Channel Message Duration Bucket",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(increase(indexer_service_channel_message_duration_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}