{
 "title": "Main  Dashboard (general)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Reward",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "indexer",
     "queryText": "{\n  indexer(id: \"0xe6368e677871b288294536c8fe6cb1bbeb19f7a2\", orderBy: rewardsEarned, orderDirection: desc) {\n    id\n    account{\n      names {\n        name\n      }\n    }\n    rewardsEarned\n    queryFeesCollected\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Query Fees",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "indexer",
     "queryText": "{\n  indexer(id: \"0xe6368e677871b288294536c8fe6cb1bbeb19f7a2\", orderBy: rewardsEarned, orderDirection: desc) {\n    id\n    account{\n      names {\n        name\n      }\n    }\n    rewardsEarned\n    queryFeesCollected\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Queries  (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_count[1m])) by (deployment)",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  },
  {
   "title": "Service Queries Total vs Failed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_service_queries_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Service Cost Model Batch Queries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(indexer_service_cost_model_batch_queries[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks Processed per Minute (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_sum[1m]))"
    }
   ]
  },
  {
   "title": "Subgraphs Total ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  d.deployment as deployment,\r\n  d.latest_ethereum_block_number as latest_block,\r\n  (case when d.synced then '✔' else '-' end) as synced,\r\n  (case when a.node_id like '%node%' then  replace(a.node_id, 'index_node_','')\r\n   else 'stopped' end) as nodeId,\r\n  n.head_block_number as mainnet_block,\r\n  ((n.head_block_number - d.latest_ethereum_block_number)/4)::decimal as lag,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     ethereum_networks  as n\r\nwhere\r\nd.id = a.id\r\nand n.name = 'mainnet'"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  d.deployment as deployment,\r\n  d.latest_ethereum_block_number as latest_block,\r\n  (case when d.synced then '✔' else '-' end) as synced,\r\n  (case when a.node_id like '%node%' then  replace(a.node_id, 'index_node_','')\r\n   else 'stopped' end) as nodeId,\r\n  n.head_block_number as mainnet_block,\r\n  ((n.head_block_number - d.latest_ethereum_block_number)/4)::decimal as lag,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     ethereum_networks  as n\r\nwhere\r\nd.id = a.id\r\nand n.name = 'mainnet'\r\nand d.failed"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  d.deployment as deployment,\r\n  d.latest_ethereum_block_number as latest_block,\r\n  (case when d.synced then '✔' else '-' end) as synced,\r\n  (case when a.node_id like '%node%' then  replace(a.node_id, 'index_node_','')\r\n   else 'stopped' end) as nodeId,\r\n  n.head_block_number as mainnet_block,\r\n  ((n.head_block_number - d.latest_ethereum_block_number)/4)::decimal as lag,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     ethereum_networks  as n\r\nwhere\r\nd.id = a.id\r\nand n.name = 'mainnet'\r\nand not d.failed"
    }
   ]
  },
  {
   "title": "Service Queries Total ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_queries_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Service Indexer Error",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(indexer_error[5m])", "legendFormat": "{{job}}-{{code}}" }
   ]
  },
  {
   "title": "Service Channel Message Total",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(indexer_service_channel_messages_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks behind over time (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(deployment_blocks_behind)" }
   ]
  },
  {
   "title": "GRT per DAI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cost_model_automation_grt_per_dai"
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  d.deployment as deployment,\r\n  d.latest_ethereum_block_number as latest_block,\r\n  (case when d.synced then '✔' else '-' end) as synced,\r\n  (case when a.node_id like '%node%' then  replace(a.node_id, 'index_node_','')\r\n   else 'stopped' end) as nodeId,\r\n  n.head_block_number as mainnet_block,\r\n  ((n.head_block_number - d.latest_ethereum_block_number)/4)::decimal as lag,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     ethereum_networks  as n\r\nwhere\r\nd.id = a.id\r\nand n.name = 'mainnet'\r\nand a.node_id = 'removed'"
    }
   ]
  },
  {
   "title": "Subgraph Block vs. Network Block",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\r\n  d.deployment as deployment,\r\n  d.latest_ethereum_block_number as latest_block,\r\n  (case when d.synced then '✔' else '-' end) as synced,\r\n  (case when a.node_id like '%node%' then  replace(a.node_id, 'index_node_','')\r\n   else 'stopped' end) as nodeId,\r\n  n.head_block_number as mainnet_block,\r\n  ((n.head_block_number - d.latest_ethereum_block_number)/4)::decimal as lag,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     ethereum_networks  as n\r\nwhere\r\nd.id = a.id\r\nand n.name = 'mainnet'"
    }
   ]
  },
  {
   "title": "Fatal errors",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  vid, block_hash, subgraph_id, message, handler, created_at\nFROM subgraphs.subgraph_error\nORDER BY vid DESC"
    }
   ]
  },
  {
   "title": "Subgraph Node Assignments",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select replace(a.node_id, 'index_node_', '') as nodeId,\n       count(*) as num_assigned,\n       array_agg(d.deployment) as deployments\n  from subgraphs.subgraph_deployment_assignment as a,\n       subgraphs.subgraph_deployment as d\n where a.id = d.id\n group by node_id\n order by node_id asc;"
    }
   ]
  },
  {
   "title": "Deployed subgraphs that have not started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select now() as time, count(*) as num_subgraphs\n   from (\n   select d.id, d.latest_ethereum_block_number block\n     from subgraphs.subgraph_deployment d,\n          subgraphs.subgraph_deployment_assignment a\n    where d.id = a.id\n    and not d.failed) a\n   where a.block < 100;\n"
    }
   ]
  },
  {
   "title": "Network Head Blocks",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  head_block_number AS \"block_number\",\n  head_block_hash AS \"block_hash\"\nFROM ethereum_networks\nWHERE head_block_number is not  null\nORDER BY name;"
    }
   ]
  }
 ]
}