{
 "title": "Subgraph Query Metrics (New)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "</br>\n<center> \n  <h1>GraphQL Server</h1> \n</center>"
   }
  },
  {
   "title": "Query Execution Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(query_execution_time_count) by (deployment)"
    }
   ]
  },
  {
   "title": "Query Execution Bucket",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Execution Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_count[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Query Execution Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_count[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(query_execution_time_count[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(query_execution_time_count[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}