global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'graph-node'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'query-node-0'
    scrape_interval: 5s
    static_configs:
      - targets: ['query-node-0:8040']
  
  - job_name: 'index-node-0'
    scrape_interval: 5s
    static_configs:
      - targets: ['index-node-0:8040']

  - job_name: 'index-node-1'
    scrape_interval: 5s
    static_configs:
      - targets: ['index-node-1:8040']

  - job_name: 'indexer-service-0'
    scrape_interval: 5s
    static_configs:
      - targets: ['indexer-service-0:7300']
