{
 "title": "Subgraph Indexing Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "select subgraph from deployment_schemas where id > 0"
   },
   {
    "name": "handler",
    "query": "label_values(deployment_handler_execution_time_bucket{deployment=\"[[deployment]]\"}, handler)"
   },
   {
    "name": "host_fn",
    "query": "label_values(deployment_host_fn_execution_time_bucket{deployment=\"[[deployment]]\"}, host_fn_name)"
   },
   { "name": "network", "query": "ethereum_chain_head_number" }
  ]
 },
 "panels": [
  {
   "title": "Time spent while indexing",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\"}[1y]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"unknown\"}[1y]))",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"scan_blocks\"}[1y]))",
     "legendFormat": "scan_blocks"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"module_init\"}[1y]))",
     "legendFormat": "module_init"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"run_handler\"}[1y]))",
     "legendFormat": "run_handler"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"transact_block\"}[1y]))",
     "legendFormat": "transact_block"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_other\"}[1y]))",
     "legendFormat": "host_export_other"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_store_get\"}[1y]))",
     "legendFormat": "host_export_store_get"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_store_set\"}[1y]))",
     "legendFormat": "host_export_store_set"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_ethereum_call\"}[1y]))",
     "legendFormat": "host_export_ethereum_call"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_ipfs_cat\"}[1y]))",
     "legendFormat": "host_export_ipfs_cat"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_ipfs_map\"}[1y]))",
     "legendFormat": "host_export_ipfs_map"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"store_get_asc_new\"}[1y]))",
     "legendFormat": "store_get_asc_new"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"apply_entity_modifications\"}[1y]))",
     "legendFormat": "apply_entity_modifications"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"check_interface_entity_uniqueness\"}[1y]))",
     "legendFormat": "check_interface_entity_uniqueness"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"apply_entity_modifications_update\"}[1y]))",
     "legendFormat": "apply_entity_modifications_update"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"apply_entity_modifications_insert\"}[1y]))",
     "legendFormat": "apply_entity_modifications_insert"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"as_modifications\"}[1y]))",
     "legendFormat": "as_modifications"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"entity_cache_evict\"}[1y]))",
     "legendFormat": "entity_cache_evict"
    }
   ]
  },
  {
   "title": "Eth Rpc Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_eth_rpc_request_duration{deployment=\"[[deployment]]\"}[1m])) by (method) * 1000",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Last Reverted Block Number",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(deployment_reverted_blocks{deployment=\"[[deployment]]\"}[1m])",
     "legendFormat": "number of reverted blocks"
    },
    {
     "expr": "deployment_reverted_blocks{deployment=\"[[deployment]]\"}",
     "legendFormat": "last reverted block number"
    }
   ]
  },
  {
   "title": "Total time waiting for DB connection",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "deployment_get_entity_conn_secs{deployment=\"subgraphs\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<br/> \n<center> \n  <h1>Block Processing / Handler Execution</h1> \n</center>"
   },
   "content": "<br/> \n<center> \n  <h1>Block Processing / Handler Execution</h1> \n</center>"
  },
  {
   "title": "Blocks Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_sum{deployment=\"[[deployment]]\"}[1m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block Processing Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transact Block Ops Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(deployment_transact_block_operations_duration_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[[host_fn]] Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(deployment_host_fn_execution_time_bucket{deployment=\"[[deployment]]\",host_fn_name=\"[[host_fn]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Host Function Triggered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_host_fn_execution_time_sum{deployment=\"[[deployment]]\"}[1m])) by (host_fn_name)",
     "legendFormat": "{{host_fn_name}}"
    }
   ]
  },
  {
   "title": "Block Trigger Count",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(deployment_block_trigger_count_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[[handler]] Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(deployment_handler_execution_time_bucket{deployment=\"[[deployment]]\",handler=\"[[handler]]\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Handler Triggered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_handler_execution_time_sum{deployment=\"[[deployment]]\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 64 },
   "options": {
    "content": "</br>\n<center> \n  <h1>GraphQL Server</h1> \n</center>"
   },
   "content": "</br>\n<center> \n  <h1>GraphQL Server</h1> \n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 64 },
   "options": {
    "content": "<br/> \n<center> \n  <h1>Block Ingestor</h1> \n</center>"
   },
   "content": "<br/> \n<center> \n  <h1>Block Ingestor</h1> \n</center>"
  },
  {
   "title": "Query Execution Time Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Execution Time Histogram ([[deployment]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 66 },
   "repeat": "deployment",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "type": "table-old",
   "description": "block_ingestor_panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "targets": [
    { "expr": "ethereum_chain_head_number{}", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Block Syncing Rate",
   "type": "graph",
   "description": "block_ingestor_panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ethereum_chain_head_number{kubernetes_pod_name=\"index-node-0\"}[1m])) by (network)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Queries  (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_count[1m])) by (deployment)",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  },
  {
   "title": "Query Rate (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "locale", "label": "Queries per minute" }
   ],
   "targets": [
    {
     "expr": "sum(rate(query_execution_time_count[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Failed Queries  (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(query_failed_execution_time_count[1m])",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  }
 ]
}