[store]

[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres-graph:5432/graph-node"
pool_size = 10

[chains]
ingestor = "index_node_0"

[chains.goerli]
shard = "primary"
provider = [{ label = "goerli-1-full", url = "http://<>:28545", features = [ "archive", "traces" ] },
            { label = "goerli-1-archive", url = "http://<>:28545", features = [ "archive" ] }]

[chains.gnosis]
shard = "primary"
provider = [{ label = "gnosis-1-full", url = "http://<>:18545", features = [ "archive", "traces" ] },
            { label = "gnosis-1-archive", url = "http://<>:18545", features = [ "archive" ] }]


[deployment]

[[deployment.rule]]
match = { network = "goerli" }
indexers = [ "index_node_0" ]

[[deployment.rule]]
indexers = [ "index_node_0" ]

[general]
query = "query_node_0"
